# permissions for end users to view execers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: execer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: execer-viewer-role
rules:
- apiGroups:
  - executors.schizo.io
  resources:
  - execers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - executors.schizo.io
  resources:
  - execers/status
  verbs:
  - get
