apiVersion: executors.schizo.io/v1alpha1
kind: Execer
metadata:
  labels:
    app.kubernetes.io/name: execer
    app.kubernetes.io/instance: execer-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: execer-sample
spec:
  # TODO(user): Add fields here
